version: '3'

networks:
    laravel:

services:
    nginx:
    image: nginx:stable-alpine
    conainter_name: nginx
    ports:
        - "80:80"
        - "4433:443"
    volumes:
        - ./src:/var/www/html
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - php
        - mysql
    networks:
        - laravel

mysql:
    image: 'mysql/mysql-server:latest'
    container_name: fablab-manager-mysql
    restart: always
    tty: true
    ports:
        - "3306:3306"
    environment:
        MYSQL_DATABASE: fablab-manager
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
        SERVICE_TAGS: prod
        SERVICE_NAME: mysql
    networks:
        - laravel
